SELECT TRUNCATE(SUM(LAT_N), 4)
FROM STATION
WHERE LAT_N > 38.7880 AND LAT_N < 137.2345;

SELECT TRUNCATE(MAX(LAT_N), 4)
FROM STATION
WHERE LAT_N < 137.2345;

--- 1:1 LAT-LONG 대응 관계 조건일 경우 ---
SELECT ROUND(LONG_W, 4)
FROM STATION
WHERE LAT_N < 137.2345
ORDER BY LAT_N DESC
LIMIT 1;

--- 1:다 LAT-LONG 대응 관계일 경우 ---
SELECT ROUND(LONG_W, 4)
FROM STATION
WHERE LAT_N = (SELECT MAX(LAT_N) FROM STATION WHERE LAT_N < 137.2345);

SELECT ROUND(MIN(LAT_N), 4)
FROM STATION
WHERE LAT_N > 38.7780;

SELECT ROUND(LONG_W, 4)
FROM STATION
WHERE LAT_N = (SELECT MIN(LAT_N) FROM STATION WHERE LAT_N > 38.778);

SELECT ROUND(ABS(MIN(LAT_N) - MAX(LAT_N)) + ABS(MIN(LONG_W) - MAX(LONG_W)), 4)
FROM STATION;

SELECT ROUND(SQRT(POWER(MAX(LAT_N)  - MIN(LAT_N),  2) + POWER(MAX(LONG_W) - MIN(LONG_W), 2)), 4)
FROM STATION;

--- MySQL 8.0 버전부터 지원하는 Rank() 함수 ---
SELECT ROUND(LAT_N, 4)
FROM (SELECT LAT_N, PERCENT_RANK() OVER (ORDER BY LAT_N) AS PERCENT FROM STATION ) AS SUB
WHERE SUB.PERCENT = 0.5;

SELECT SUM(city.population)
FROM CITY as city LEFT JOIN COUNTRY as country ON city.countrycode = country.code
WHERE country.continent = 'Asia';

SELECT city.name
FROM CITY as city LEFT JOIN COUNTRY as country on city.countrycode = country.code
WHERE country.continent = 'Africa';