-- 정규식을 활용한 풀이 --
SELECT ANIMAL.ANIMAL_ID, ANIMAL.NAME, ANIMAL.SEX_UPON_INTAKE
FROM ANIMAL_INS ANIMAL
WHERE NAME REGEXP "^(Lucy|Ella|Pickle|Rogan|Sabrina|Mitty)$"
ORDER BY ANIMAL_ID;

-- WHERE IN을 활용한 풀이 --
SELECT ANIMAL.ANIMAL_ID, ANIMAL.NAME, ANIMAL.SEX_UPON_INTAKE
FROM ANIMAL_INS ANIMAL
WHERE NAME IN ("Lucy", "Ella", "Pickle", "Rogan", "Sabrina", "Mitty")
ORDER BY ANIMAL.ANIMAL_ID;